/**
 * Auto-migration — runs ONCE per Vercel function instance (cold start).
 * All 61 ALTER TABLE IF NOT EXISTS statements are batched into a single
 * raw SQL call so there is zero per-request overhead after the first call.
 *
 * "ran" is module-level so it persists for the lifetime of the function
 * instance (typically minutes to hours on Vercel), meaning warm requests
 * pay zero cost. Cold starts pay one batched DB round-trip (~50-100ms).
 */

import { db } from "./db";

let ran = false;

// All migrations in one semicolon-separated string — single round-trip to DB
const MIGRATION_SQL = `
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "rangeColor" TEXT NOT NULL DEFAULT '#f5b400';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "reviewTextSize" INTEGER NOT NULL DEFAULT 14;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "reviewTextAlign" TEXT NOT NULL DEFAULT 'left';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "headingFontSize" INTEGER NOT NULL DEFAULT 11;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "headingBold" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "headingAlign" TEXT NOT NULL DEFAULT 'left';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "showBorder" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "borderColor" TEXT NOT NULL DEFAULT '#e0e0e0';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "borderWidth" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "borderStyle" TEXT NOT NULL DEFAULT 'solid';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "backgroundGradient" TEXT;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "primaryGradient" TEXT;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "letCustomerPickLanguage" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "enabledLanguages" TEXT[] DEFAULT ARRAY['en']::TEXT[];
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "formTemplate" TEXT NOT NULL DEFAULT 'basic';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "summaryLayout" TEXT NOT NULL DEFAULT 'modern';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "summaryBgColor" TEXT NOT NULL DEFAULT '#f8f8f8';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "summaryTextColor" TEXT NOT NULL DEFAULT '#333333';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "summaryWidth" INTEGER NOT NULL DEFAULT 220;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "summaryPosition" TEXT NOT NULL DEFAULT 'left';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "filterBgColor" TEXT NOT NULL DEFAULT '#ffffff';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "filterTextColor" TEXT NOT NULL DEFAULT '#999999';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "filterBorderColor" TEXT NOT NULL DEFAULT 'rgba(0,0,0,0.08)';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "sortBgColor" TEXT NOT NULL DEFAULT '#ffffff';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "sortTextColor" TEXT NOT NULL DEFAULT '#333333';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "sortBorderColor" TEXT NOT NULL DEFAULT '#dddddd';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "reviewCountFontSize" INTEGER NOT NULL DEFAULT 14;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "reviewTitleColor" TEXT NOT NULL DEFAULT '#111111';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "reviewBodyColor" TEXT NOT NULL DEFAULT '#333333';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "reviewMetaColor" TEXT NOT NULL DEFAULT '#999999';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "formBgColor" TEXT NOT NULL DEFAULT '#ffffff';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "formTextColor" TEXT NOT NULL DEFAULT '#1a1a2e';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "formCloseColor" TEXT NOT NULL DEFAULT '#999999';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "ratingBadgeStarSize" INTEGER NOT NULL DEFAULT 16;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "ratingBadgeTemplate" TEXT NOT NULL DEFAULT '{rating}';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "splitSummary" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "reviewTitle" TEXT;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "recommends" BOOLEAN;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "reviewTitle" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "recommends" BOOLEAN;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "displayStyle" TEXT NOT NULL DEFAULT 'list';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "primaryColor" TEXT NOT NULL DEFAULT '#111111';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "starColor" TEXT NOT NULL DEFAULT '#f5b400';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "backgroundColor" TEXT NOT NULL DEFAULT '#ffffff';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "textColor" TEXT NOT NULL DEFAULT '#333333';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "fontFamily" TEXT NOT NULL DEFAULT 'inherit';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "borderRadius" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "arrowColor" TEXT NOT NULL DEFAULT '#111111';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "gridColumns" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "carouselVisible" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "formAlign" TEXT NOT NULL DEFAULT 'left';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "formMaxWidth" INTEGER NOT NULL DEFAULT 540;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "widgetMaxWidth" INTEGER NOT NULL DEFAULT 900;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "widgetTitle" TEXT NOT NULL DEFAULT 'Customer Reviews';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "topSpacing" INTEGER NOT NULL DEFAULT 24;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "reviewTextSize" INTEGER NOT NULL DEFAULT 14;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "reviewTextAlign" TEXT NOT NULL DEFAULT 'left';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "reviewCountFontSize" INTEGER NOT NULL DEFAULT 14;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "showSuggestionsOnWebsite" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "showSuggestionsOnQr" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "suggestionLanguage" TEXT NOT NULL DEFAULT 'en'
`;

export async function runAutoMigrations() {
  if (ran) return;   // warm request — skip entirely
  ran = true;
  try {
    // Single DB round-trip for all column additions
    await db.$executeRawUnsafe(MIGRATION_SQL);
    console.log("[rivu] migrations ok");
  } catch (err) {
    // Log but don't crash — IF NOT EXISTS means partial success is fine
    console.error("[rivu] migration error:", err);
  }
}
